### ISSUE TITLE
are you planning to relase the inference codes for VideoGPT-plus_LLaMA3-8B-8k and/or VideoGPT-plus_Vicuna-7B-4k

### ISSUE THREAD

**Issue by pritamqu** [mbzuai-oryx/VideoGPT-plus#5]
are you planning to release the inference codes for 

- MBZUAI/VideoGPT-plus_LLaMA3-8B-8k
- MBZUAI/VideoGPT-plus_Vicuna-7B-4k

**Comment by mmaaz60** [comment]
Hi @pritamqu,

I appreciate your interest in our work. Currently, there are no such plans because of some ongoing commitments. However, please note that the `LLaMA-3` implementation is based on [LLaVA++](https://github.com/mbzuai-oryx/LLaVA-pp) project, and Vicuna implementation is based on original official [LLaVA](https://github.com/haotian-liu/LLaVA) implementation.

I hope it will help.
